name: CI Check and Build

on:
  pull_request:
    branches: [master]

jobs:
  ci-check-and-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run ci-check
        run: pnpm run ci-check

      - name: Build project
        run: pnpm run build
